"""add_license_model_and_user_fields

Revision ID: 51cb514d2b47
Revises: 944ac9b5d2eb
Create Date: 2026-01-05 15:34:14.698359

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "51cb514d2b47"
down_revision: str | None = "944ac9b5d2eb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create licenses table first
    op.create_table(
        "licenses",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("key", sa.String(64), unique=True, index=True, nullable=False),
        sa.Column("type", sa.String(20), nullable=False, server_default="basic"),
        sa.Column("status", sa.String(20), nullable=False, server_default="active"),
        sa.Column("max_users", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("max_transactions_per_month", sa.Integer(), nullable=True),
        sa.Column("max_documents_per_month", sa.Integer(), nullable=True),
        sa.Column("has_ai_assistant", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("has_insights", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("has_debt_strategies", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("has_goals", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("has_budget", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
    )

    # Add is_admin with default value for existing rows
    # Use batch mode for SQLite compatibility
    with op.batch_alter_table("users") as batch_op:
        batch_op.add_column(
            sa.Column("is_admin", sa.Boolean(), nullable=False, server_default="false")
        )
        batch_op.add_column(sa.Column("license_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_users_license_id", "licenses", ["license_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite compatibility
    with op.batch_alter_table("users") as batch_op:
        batch_op.drop_constraint("fk_users_license_id", type_="foreignkey")
        batch_op.drop_column("license_id")
        batch_op.drop_column("is_admin")
    op.drop_table("licenses")
    # ### end Alembic commands ###
