"""add reset_token to users

Revision ID: 637898c1dca0
Revises: add_license_code_inv
Create Date: 2026-01-06 12:28:09.032222

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "637898c1dca0"
down_revision: str | None = "add_license_code_inv"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("licenses") as batch_op:
        batch_op.drop_constraint("uq_licenses_code", type_="unique")
        batch_op.drop_index("ix_licenses_code")
        batch_op.create_index(batch_op.f("ix_licenses_code"), ["code"], unique=True)
    op.add_column("users", sa.Column("reset_token", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "reset_token")
    with op.batch_alter_table("licenses") as batch_op:
        batch_op.drop_index(batch_op.f("ix_licenses_code"))
        batch_op.create_index("ix_licenses_code", ["code"], unique=False)
        batch_op.create_unique_constraint("uq_licenses_code", ["code"])
    # ### end Alembic commands ###
