"""add_envelopes_automations

Revision ID: ba9ea6b64409
Revises: add_notifications
Create Date: 2026-01-18 23:01:39.353389

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba9ea6b64409"
down_revision: str | None = "add_notifications"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "automation_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("trigger_type", sa.String(length=20), nullable=False),
        sa.Column("trigger_config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("conditions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("action_type", sa.String(length=20), nullable=False),
        sa.Column("action_config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("last_executed_at", sa.DateTime(), nullable=True),
        sa.Column("execution_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("max_consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("auto_disabled_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("ownership_type", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_automation_rules_trigger_type", "automation_rules", ["trigger_type"], unique=False
    )
    op.create_index(
        "ix_automation_rules_user_active",
        "automation_rules",
        ["user_id", "is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_automation_rules_user_id"), "automation_rules", ["user_id"], unique=False
    )
    op.create_table(
        "automation_executions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rule_id", sa.Integer(), nullable=False),
        sa.Column("executed_at", sa.DateTime(), nullable=False),
        sa.Column("trigger_reason", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("result_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("error_details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("conditions_met", sa.Boolean(), nullable=True),
        sa.Column("conditions_result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["rule_id"], ["automation_rules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_automation_executions_rule_date",
        "automation_executions",
        ["rule_id", "executed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_automation_executions_rule_id"), "automation_executions", ["rule_id"], unique=False
    )
    op.create_table(
        "spending_envelopes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("period_type", sa.String(length=20), nullable=False),
        sa.Column("limit_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("current_balance", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("period_start_date", sa.Date(), nullable=False),
        sa.Column("period_end_date", sa.Date(), nullable=False),
        sa.Column("allow_rollover", sa.Boolean(), nullable=False),
        sa.Column("max_rollover_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("rollover_balance", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("refill_schedule", sa.String(length=30), nullable=False),
        sa.Column("custom_refill_day", sa.Integer(), nullable=True),
        sa.Column("auto_refill", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("color", sa.String(length=20), nullable=True),
        sa.Column("icon", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("ownership_type", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_envelopes_user_active", "spending_envelopes", ["user_id", "is_active"], unique=False
    )
    op.create_index(
        "ix_envelopes_user_category", "spending_envelopes", ["user_id", "category_id"], unique=False
    )
    op.create_index(
        op.f("ix_spending_envelopes_category_id"),
        "spending_envelopes",
        ["category_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_spending_envelopes_user_id"), "spending_envelopes", ["user_id"], unique=False
    )
    op.create_table(
        "envelope_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("envelope_id", sa.Integer(), nullable=False),
        sa.Column("transaction_id", sa.Integer(), nullable=True),
        sa.Column("change_type", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("balance_before", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("notes", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["envelope_id"], ["spending_envelopes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["transaction_id"], ["transactions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_envelope_history_envelope_date",
        "envelope_history",
        ["envelope_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_envelope_history_envelope_id"), "envelope_history", ["envelope_id"], unique=False
    )
    op.create_index(
        op.f("ix_envelope_history_transaction_id"),
        "envelope_history",
        ["transaction_id"],
        unique=False,
    )
    op.drop_index("ix_categories_parent_id", table_name="categories")
    op.drop_index("ix_categories_user_id", table_name="categories")
    op.drop_index("ix_credit_card_invoices_period", table_name="credit_card_invoices")
    op.drop_index("ix_credit_card_invoices_status", table_name="credit_card_invoices")
    op.drop_index("ix_invoices_card_period", table_name="credit_card_invoices")
    op.drop_index("ix_invoices_payment_account", table_name="credit_card_invoices")
    op.drop_index("ix_invoices_user_period", table_name="credit_card_invoices")
    op.drop_index("ix_invoices_user_status", table_name="credit_card_invoices")
    op.drop_constraint("uq_credit_card_account", "credit_cards", type_="unique")
    op.drop_index("ix_credit_cards_account_id", table_name="credit_cards")
    op.create_index(op.f("ix_credit_cards_account_id"), "credit_cards", ["account_id"], unique=True)
    op.drop_index("ix_debts_user_status", table_name="debts")
    op.drop_index("ix_documents_user_created", table_name="documents")
    op.drop_index("ix_documents_user_status", table_name="documents")
    op.drop_index("ix_goals_user_status", table_name="goals")
    op.drop_index("ix_income_sources_user_active", table_name="income_sources")
    op.drop_index("ix_installment_series_merchant", table_name="installment_series")
    op.drop_index("ix_installment_series_user_status", table_name="installment_series")
    op.drop_index("ix_merchants_cnpj", table_name="merchants")
    op.add_column(
        "notifications",
        sa.Column("extra_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.drop_column("notifications", "metadata")
    op.drop_index("ix_recurring_user_status", table_name="recurring_transactions")
    op.create_index(
        op.f("ix_recurring_transactions_account_id"),
        "recurring_transactions",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recurring_transactions_category_id"),
        "recurring_transactions",
        ["category_id"],
        unique=False,
    )
    op.drop_index("ix_transactions_credit_card_user", table_name="transactions")
    op.drop_index("ix_transactions_merchant_id", table_name="transactions")
    op.drop_index("ix_transactions_user_date", table_name="transactions")
    op.drop_index("ix_transactions_user_fixed", table_name="transactions")
    op.drop_index("ix_transactions_user_is_paid", table_name="transactions")
    op.drop_index("ix_transactions_user_payment_method", table_name="transactions")
    op.drop_index("ix_transactions_user_recurring", table_name="transactions")
    op.drop_index("ix_transactions_user_type", table_name="transactions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_transactions_user_type", "transactions", ["user_id", "type"], unique=False)
    op.create_index(
        "ix_transactions_user_recurring", "transactions", ["user_id", "is_recurring"], unique=False
    )
    op.create_index(
        "ix_transactions_user_payment_method",
        "transactions",
        ["user_id", "payment_method"],
        unique=False,
    )
    op.create_index(
        "ix_transactions_user_is_paid", "transactions", ["user_id", "is_paid"], unique=False
    )
    op.create_index(
        "ix_transactions_user_fixed", "transactions", ["user_id", "is_fixed"], unique=False
    )
    op.create_index("ix_transactions_user_date", "transactions", ["user_id", "date"], unique=False)
    op.create_index("ix_transactions_merchant_id", "transactions", ["merchant_id"], unique=False)
    op.create_index(
        "ix_transactions_credit_card_user",
        "transactions",
        ["credit_card_id", "user_id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_recurring_transactions_category_id"), table_name="recurring_transactions"
    )
    op.drop_index(op.f("ix_recurring_transactions_account_id"), table_name="recurring_transactions")
    op.create_index(
        "ix_recurring_user_status", "recurring_transactions", ["user_id", "status"], unique=False
    )
    op.add_column(
        "notifications",
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("notifications", "extra_data")
    op.create_index("ix_merchants_cnpj", "merchants", ["cnpj"], unique=False)
    op.create_index(
        "ix_installment_series_user_status",
        "installment_series",
        ["user_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_installment_series_merchant", "installment_series", ["merchant_id"], unique=False
    )
    op.create_index(
        "ix_income_sources_user_active", "income_sources", ["user_id", "is_active"], unique=False
    )
    op.create_index("ix_goals_user_status", "goals", ["user_id", "status"], unique=False)
    op.create_index("ix_documents_user_status", "documents", ["user_id", "status"], unique=False)
    op.create_index(
        "ix_documents_user_created", "documents", ["user_id", "created_at"], unique=False
    )
    op.create_index("ix_debts_user_status", "debts", ["user_id", "status"], unique=False)
    op.drop_index(op.f("ix_credit_cards_account_id"), table_name="credit_cards")
    op.create_index("ix_credit_cards_account_id", "credit_cards", ["account_id"], unique=False)
    op.create_unique_constraint("uq_credit_card_account", "credit_cards", ["account_id"])
    op.create_index(
        "ix_invoices_user_status", "credit_card_invoices", ["user_id", "status"], unique=False
    )
    op.create_index(
        "ix_invoices_user_period",
        "credit_card_invoices",
        ["user_id", "reference_year", "reference_month"],
        unique=False,
    )
    op.create_index(
        "ix_invoices_payment_account", "credit_card_invoices", ["payment_account_id"], unique=False
    )
    op.create_index(
        "ix_invoices_card_period",
        "credit_card_invoices",
        ["credit_card_id", "reference_year", "reference_month"],
        unique=False,
    )
    op.create_index(
        "ix_credit_card_invoices_status", "credit_card_invoices", ["status"], unique=False
    )
    op.create_index(
        "ix_credit_card_invoices_period",
        "credit_card_invoices",
        ["reference_year", "reference_month"],
        unique=False,
    )
    op.create_index("ix_categories_user_id", "categories", ["user_id"], unique=False)
    op.create_index("ix_categories_parent_id", "categories", ["parent_id"], unique=False)
    op.drop_index(op.f("ix_envelope_history_transaction_id"), table_name="envelope_history")
    op.drop_index(op.f("ix_envelope_history_envelope_id"), table_name="envelope_history")
    op.drop_index("ix_envelope_history_envelope_date", table_name="envelope_history")
    op.drop_table("envelope_history")
    op.drop_index(op.f("ix_spending_envelopes_user_id"), table_name="spending_envelopes")
    op.drop_index(op.f("ix_spending_envelopes_category_id"), table_name="spending_envelopes")
    op.drop_index("ix_envelopes_user_category", table_name="spending_envelopes")
    op.drop_index("ix_envelopes_user_active", table_name="spending_envelopes")
    op.drop_table("spending_envelopes")
    op.drop_index(op.f("ix_automation_executions_rule_id"), table_name="automation_executions")
    op.drop_index("ix_automation_executions_rule_date", table_name="automation_executions")
    op.drop_table("automation_executions")
    op.drop_index(op.f("ix_automation_rules_user_id"), table_name="automation_rules")
    op.drop_index("ix_automation_rules_user_active", table_name="automation_rules")
    op.drop_index("ix_automation_rules_trigger_type", table_name="automation_rules")
    op.drop_table("automation_rules")
    # ### end Alembic commands ###
